version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - WAZUH_USER=admin
      - WAZUH_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://100.79.144.59:9200/wazuh-alerts-*/_search
    volumes:
      - ./app/data:/app/data  # Mount host app/data to container /app/data
      - ./app/model:/app/model  # Mount host app/model to container /app/model
    restart: always
