version: '3.8'

services:
  transformer-detection:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ../data:/app/data
    env_file:
      - ../utils/.env.local
    restart: always
