[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
loglevel=info

[program:cron]
command=cron -f
autostart=true
autorestart=true
stdout_logfile=/var/log/cron.log
stderr_logfile=/var/log/cron_error.log

[program:fastapi]
command=uvicorn api.app:app --host 0.0.0.0 --port 8000
autostart=true
autorestart=true
stdout_logfile=/var/log/fastapi.log
stderr_logfile=/var/log/fastapi_error.log

[program:dash]
command=python app.py
autostart=true
autorestart=true
stdout_logfile=/var/log/dash.log
stderr_logfile=/var/log/dash_error.log
